project_id = "prpvoabbenonecgzufhb"

[functions.bitrix-install]
verify_jwt = false

[functions.bitrix-uninstall]
verify_jwt = false

[functions.bitrix-payment-iframe]
verify_jwt = false

[functions.bitrix-payment-process]
verify_jwt = false

[functions.bitrix-refresh-token]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.bitrix-auth]
verify_jwt = false

[functions.bitrix-config]
verify_jwt = false
